name = "lean-banach-tarski"
version = "0.1.0"
defaultTargets = ["lean-banach-tarski"]

[[lean_lib]]
name = "LeanBanachTarski"

[[lean_exe]]
name = "lean-banach-tarski"
root = "Main"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"
